<?php
/**
 * CalendarsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * APPrise Mobile API
 *
 * API for APPrise Mobile Clients
 *
 * OpenAPI spec version: 2.0.0
 * Contact: customercare@apprise-mobile.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CalendarsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CalendarsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for calendarsGet
     *
     * finds calendars in the system.
     *
     */
    public function testCalendarsGet()
    {

    }

    /**
     * Test case for calendarsIdDelete
     *
     * delete a calendar.
     *
     */
    public function testCalendarsIdDelete()
    {

    }

    /**
     * Test case for calendarsIdGet
     *
     * gets calendar by id in the system.
     *
     */
    public function testCalendarsIdGet()
    {

    }

    /**
     * Test case for calendarsIdPut
     *
     * edit a calendar with the given id.
     *
     */
    public function testCalendarsIdPut()
    {

    }

    /**
     * Test case for calendarsPost
     *
     * Add a new calendar to the account.
     *
     */
    public function testCalendarsPost()
    {

    }

}
