<?php
/**
 * ContentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * APPrise Mobile API
 *
 * API for APPrise Mobile Clients
 *
 * OpenAPI spec version: 2.0.0
 * Contact: customercare@apprise-mobile.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ContentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for contentsGet
     *
     * finds content in the system.
     *
     */
    public function testContentsGet()
    {

    }

    /**
     * Test case for contentsIdDelete
     *
     * delete a content.
     *
     */
    public function testContentsIdDelete()
    {

    }

    /**
     * Test case for contentsIdGet
     *
     * gets content by id in the system.
     *
     */
    public function testContentsIdGet()
    {

    }

    /**
     * Test case for contentsIdPut
     *
     * edit a content with the given id.
     *
     */
    public function testContentsIdPut()
    {

    }

    /**
     * Test case for contentsPost
     *
     * Add a new content to the account.
     *
     */
    public function testContentsPost()
    {

    }

}
