<?php
/**
 * EventsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * APPrise Mobile API
 *
 * API for APPrise Mobile Clients
 *
 * OpenAPI spec version: 2.0.0
 * Contact: customercare@apprise-mobile.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EventsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EventsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for eventsGet
     *
     * finds events in the system.
     *
     */
    public function testEventsGet()
    {

    }

    /**
     * Test case for eventsIdDelete
     *
     * delete an event.
     *
     */
    public function testEventsIdDelete()
    {

    }

    /**
     * Test case for eventsIdGet
     *
     * gets event by id in the system.
     *
     */
    public function testEventsIdGet()
    {

    }

    /**
     * Test case for eventsIdPut
     *
     * edit an event with the given id.
     *
     */
    public function testEventsIdPut()
    {

    }

    /**
     * Test case for eventsPost
     *
     * Add a new event to the account.
     *
     */
    public function testEventsPost()
    {

    }

}
