<?php
/**
 * ContentFeedProfileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * APPrise Mobile API
 *
 * API for APPrise Mobile Clients
 *
 * OpenAPI spec version: 2.0.0
 * Contact: customercare@apprise-mobile.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContentFeedProfileTest Class Doc Comment
 *
 * @category    Class */
// * @description ContentFeedProfile
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContentFeedProfileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ContentFeedProfile"
     */
    public function testContentFeedProfile()
    {

    }

    /**
     * Test attribute "_id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {

    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {

    }

    /**
     * Test attribute "modified_by"
     */
    public function testPropertyModifiedBy()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {

    }

    /**
     * Test attribute "long_name"
     */
    public function testPropertyLongName()
    {

    }

    /**
     * Test attribute "admins"
     */
    public function testPropertyAdmins()
    {

    }

    /**
     * Test attribute "privacy_policy"
     */
    public function testPropertyPrivacyPolicy()
    {

    }

    /**
     * Test attribute "privacy_policy_enabled"
     */
    public function testPropertyPrivacyPolicyEnabled()
    {

    }

    /**
     * Test attribute "user_registration"
     */
    public function testPropertyUserRegistration()
    {

    }

    /**
     * Test attribute "desc"
     */
    public function testPropertyDesc()
    {

    }

    /**
     * Test attribute "date_format"
     */
    public function testPropertyDateFormat()
    {

    }

    /**
     * Test attribute "primary_color"
     */
    public function testPropertyPrimaryColor()
    {

    }

    /**
     * Test attribute "logo_s3_key"
     */
    public function testPropertyLogoS3Key()
    {

    }

    /**
     * Test attribute "logo_s3_url"
     */
    public function testPropertyLogoS3Url()
    {

    }

    /**
     * Test attribute "header_color"
     */
    public function testPropertyHeaderColor()
    {

    }

    /**
     * Test attribute "social_links"
     */
    public function testPropertySocialLinks()
    {

    }

    /**
     * Test attribute "web_url"
     */
    public function testPropertyWebUrl()
    {

    }

    /**
     * Test attribute "contact_info"
     */
    public function testPropertyContactInfo()
    {

    }

    /**
     * Test attribute "home_folder"
     */
    public function testPropertyHomeFolder()
    {

    }

    /**
     * Test attribute "everyone_group"
     */
    public function testPropertyEveryoneGroup()
    {

    }

    /**
     * Test attribute "calendars"
     */
    public function testPropertyCalendars()
    {

    }

    /**
     * Test attribute "content_folders"
     */
    public function testPropertyContentFolders()
    {

    }

    /**
     * Test attribute "missing_link_folders"
     */
    public function testPropertyMissingLinkFolders()
    {

    }

    /**
     * Test attribute "missing_link_calendars"
     */
    public function testPropertyMissingLinkCalendars()
    {

    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {

    }

    /**
     * Test attribute "events"
     */
    public function testPropertyEvents()
    {

    }

    /**
     * Test attribute "groups"
     */
    public function testPropertyGroups()
    {

    }

    /**
     * Test attribute "carousel"
     */
    public function testPropertyCarousel()
    {

    }

}
