<?php
/**
 * ContentFolderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * APPrise Mobile API
 *
 * API for APPrise Mobile Clients
 *
 * OpenAPI spec version: 2.0.0
 * Contact: customercare@apprise-mobile.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContentFolderTest Class Doc Comment
 *
 * @category    Class */
// * @description ContentFolder
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContentFolderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ContentFolder"
     */
    public function testContentFolder()
    {

    }

    /**
     * Test attribute "_id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {

    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {

    }

    /**
     * Test attribute "modified_by"
     */
    public function testPropertyModifiedBy()
    {

    }

    /**
     * Test attribute "parent"
     */
    public function testPropertyParent()
    {

    }

    /**
     * Test attribute "children"
     */
    public function testPropertyChildren()
    {

    }

    /**
     * Test attribute "integration_id"
     */
    public function testPropertyIntegrationId()
    {

    }

    /**
     * Test attribute "integration_type"
     */
    public function testPropertyIntegrationType()
    {

    }

    /**
     * Test attribute "permissions"
     */
    public function testPropertyPermissions()
    {

    }

}
