<?php
/**
 * ContentFeedProfileCarouselTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * APPrise Mobile API
 *
 * API for APPrise Mobile Clients
 *
 * OpenAPI spec version: 2.0.0
 * Contact: customercare@apprise-mobile.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContentFeedProfileCarouselTest Class Doc Comment
 *
 * @category    Class */
// * @description ContentFeedProfileCarousel
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContentFeedProfileCarouselTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ContentFeedProfileCarousel"
     */
    public function testContentFeedProfileCarousel()
    {

    }

    /**
     * Test attribute "carousel_id"
     */
    public function testPropertyCarouselId()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {

    }

    /**
     * Test attribute "s3_key"
     */
    public function testPropertyS3Key()
    {

    }

    /**
     * Test attribute "small_carousel_key"
     */
    public function testPropertySmallCarouselKey()
    {

    }

    /**
     * Test attribute "medium_carousel_key"
     */
    public function testPropertyMediumCarouselKey()
    {

    }

    /**
     * Test attribute "large_carousel_key"
     */
    public function testPropertyLargeCarouselKey()
    {

    }

    /**
     * Test attribute "xlarge_carousel_key"
     */
    public function testPropertyXlargeCarouselKey()
    {

    }

}
