<?php
/**
 * ContentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * APPrise Mobile API
 *
 * API for APPrise Mobile Clients
 *
 * OpenAPI spec version: 2.0.0
 * Contact: customercare@apprise-mobile.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContentTest Class Doc Comment
 *
 * @category    Class */
// * @description Content
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Content"
     */
    public function testContent()
    {

    }

    /**
     * Test attribute "_id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {

    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "publish_date"
     */
    public function testPropertyPublishDate()
    {

    }

    /**
     * Test attribute "web_url"
     */
    public function testPropertyWebUrl()
    {

    }

    /**
     * Test attribute "s3_key"
     */
    public function testPropertyS3Key()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {

    }

    /**
     * Test attribute "modified_by"
     */
    public function testPropertyModifiedBy()
    {

    }

    /**
     * Test attribute "share"
     */
    public function testPropertyShare()
    {

    }

    /**
     * Test attribute "post_date"
     */
    public function testPropertyPostDate()
    {

    }

    /**
     * Test attribute "unpost_date"
     */
    public function testPropertyUnpostDate()
    {

    }

    /**
     * Test attribute "notes_enabled"
     */
    public function testPropertyNotesEnabled()
    {

    }

    /**
     * Test attribute "notify"
     */
    public function testPropertyNotify()
    {

    }

    /**
     * Test attribute "cacheable"
     */
    public function testPropertyCacheable()
    {

    }

    /**
     * Test attribute "content_type"
     */
    public function testPropertyContentType()
    {

    }

    /**
     * Test attribute "total_likes"
     */
    public function testPropertyTotalLikes()
    {

    }

    /**
     * Test attribute "total_comments"
     */
    public function testPropertyTotalComments()
    {

    }

    /**
     * Test attribute "total_views"
     */
    public function testPropertyTotalViews()
    {

    }

    /**
     * Test attribute "secure"
     */
    public function testPropertySecure()
    {

    }

    /**
     * Test attribute "include_in_feed"
     */
    public function testPropertyIncludeInFeed()
    {

    }

    /**
     * Test attribute "access_groups"
     */
    public function testPropertyAccessGroups()
    {

    }

    /**
     * Test attribute "content_folder"
     */
    public function testPropertyContentFolder()
    {

    }

    /**
     * Test attribute "integration_id"
     */
    public function testPropertyIntegrationId()
    {

    }

    /**
     * Test attribute "integration_type"
     */
    public function testPropertyIntegrationType()
    {

    }

    /**
     * Test attribute "permissions"
     */
    public function testPropertyPermissions()
    {

    }

    /**
     * Test attribute "hls_video_playlist_url"
     */
    public function testPropertyHlsVideoPlaylistUrl()
    {

    }

    /**
     * Test attribute "transcode_video_status"
     */
    public function testPropertyTranscodeVideoStatus()
    {

    }

    /**
     * Test attribute "thumbnail_s3_key"
     */
    public function testPropertyThumbnailS3Key()
    {

    }

    /**
     * Test attribute "small_thumbnail_url"
     */
    public function testPropertySmallThumbnailUrl()
    {

    }

    /**
     * Test attribute "medium_thumbnail_url"
     */
    public function testPropertyMediumThumbnailUrl()
    {

    }

    /**
     * Test attribute "large_thumbnail_url"
     */
    public function testPropertyLargeThumbnailUrl()
    {

    }

    /**
     * Test attribute "xlarge_thumbnail_url"
     */
    public function testPropertyXlargeThumbnailUrl()
    {

    }

    /**
     * Test attribute "thumbnail_job_id"
     */
    public function testPropertyThumbnailJobId()
    {

    }

    /**
     * Test attribute "thumbnail_job_status"
     */
    public function testPropertyThumbnailJobStatus()
    {

    }

    /**
     * Test attribute "display_thumbnail"
     */
    public function testPropertyDisplayThumbnail()
    {

    }

}
