<?php
/**
 * EventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * APPrise Mobile API
 *
 * API for APPrise Mobile Clients
 *
 * OpenAPI spec version: 2.0.0
 * Contact: customercare@apprise-mobile.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EventTest Class Doc Comment
 *
 * @category    Class */
// * @description Event
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Event"
     */
    public function testEvent()
    {

    }

    /**
     * Test attribute "_id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {

    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {

    }

    /**
     * Test attribute "modified_by"
     */
    public function testPropertyModifiedBy()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "event_time_zone"
     */
    public function testPropertyEventTimeZone()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {

    }

    /**
     * Test attribute "allday"
     */
    public function testPropertyAllday()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "notify"
     */
    public function testPropertyNotify()
    {

    }

    /**
     * Test attribute "calendar"
     */
    public function testPropertyCalendar()
    {

    }

    /**
     * Test attribute "access_groups"
     */
    public function testPropertyAccessGroups()
    {

    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {

    }

    /**
     * Test attribute "integration_id"
     */
    public function testPropertyIntegrationId()
    {

    }

    /**
     * Test attribute "integration_type"
     */
    public function testPropertyIntegrationType()
    {

    }

    /**
     * Test attribute "permissions"
     */
    public function testPropertyPermissions()
    {

    }

    /**
     * Test attribute "thumbnail_s3_key"
     */
    public function testPropertyThumbnailS3Key()
    {

    }

    /**
     * Test attribute "small_thumbnail_url"
     */
    public function testPropertySmallThumbnailUrl()
    {

    }

    /**
     * Test attribute "medium_thumbnail_url"
     */
    public function testPropertyMediumThumbnailUrl()
    {

    }

    /**
     * Test attribute "large_thumbnail_url"
     */
    public function testPropertyLargeThumbnailUrl()
    {

    }

    /**
     * Test attribute "xlarge_thumbnail_url"
     */
    public function testPropertyXlargeThumbnailUrl()
    {

    }

    /**
     * Test attribute "thumbnail_job_id"
     */
    public function testPropertyThumbnailJobId()
    {

    }

    /**
     * Test attribute "thumbnail_job_status"
     */
    public function testPropertyThumbnailJobStatus()
    {

    }

    /**
     * Test attribute "include_in_feed"
     */
    public function testPropertyIncludeInFeed()
    {

    }

    /**
     * Test attribute "display_thumbnail"
     */
    public function testPropertyDisplayThumbnail()
    {

    }

}
